name: loki-json-lab
services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - "./alloy/config.alloy:/etc/alloy/config.alloy"
      - "./nlog:/var/log/nlog"
    ports:
      - "12345:12345"  # Optional: expose Alloy's HTTP port for metrics/status
    depends_on:
      - loki
      
  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - "./loki/loki.yaml:/etc/loki/loki.yaml"
    command: -config.file=/etc/loki/loki.yaml
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki